dependencies {
    // Registrate
    api(libs.registrate)

    // Anvil Lib
    implementation(libs.anvillib)
    interfaceInjectionData(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // Curios API (OctoStudios maven down, using CurseForge fallback)
    implementation("curse.maven:curios-continuation-1037991:5888964") { transitive = false }

    // JEI
    compileOnlyApi(libs.jeiCommonApi) { transitive = false }
    compileOnlyApi(libs.jeiForgeApi) { transitive = false }
    implementation(libs.jeiForgeImpl) { transitive = false }

    // Jade
    implementation(libs.jade)

    // Patchouli
    implementation(libs.patchouli)

    // Mekanism
    runtimeOnly("mekanism:Mekanism:${mekanism_version}") { transitive = false }
    implementation("mekanism:Mekanism:${mekanism_version}:generators") { transitive = false }
    accessCompileOnly(("mekanism:Mekanism:${mekanism_version}"))

    // Mekanism-MoreMachine (via CurseMaven)
    implementation("curse.maven:mekanism-more-machine-1275257:7019511") { transitive = false }
    runtimeOnly("curse.maven:mekanism-more-machine-1275257:7019511") { transitive = false }
}